# Part 1

In [1]:
import numpy as np

In [244]:
f = open('Day4input.txt', 'r')
data = f.read()
data = data.split('\n\n')
numbers = np.array([int(i) for i in data[0].split(',')])
boards = [i.split('\n') for i in data[1:]]

In [237]:
boardsfinal = np.zeros((len(boards), 5, 5))
boardsfound = np.zeros((len(boards), 5, 5))
for m, j in enumerate(boards):
    board = [i.split(' ') for i in j]
    boardtmp = np.zeros((5, 5))
    for n,k in enumerate(board):
        boardtmp[n] = [int(i) for i in k if i != '']
    boardsfinal[m] = boardtmp

In [238]:
for i in numbers:
    hits = np.where(boardsfinal == i)
    for j in range(len(hits[0])):
        boardsfound[hits[0][j], hits[1][j], hits[2][j]] = 1
        Truetest1 = np.array([True for i in boardsfound[hits[0][j]] if sum(i) == 5])
        Truetest2 = np.array([True for i in np.transpose(boardsfound[hits[0][j]]) if sum(i) == 5])
        if Truetest1.any() == True or Truetest2.any() ==True:
            winningboard = boardsfinal[hits[0][j]]
            winningmask = boardsfound[hits[0][j]]
            break
    else:
        continue
    break
print(winningboard)
print(winningmask)
print(sum(sum(winningboard*(winningmask-1)*-1))*i)

[[24. 19. 78.  4. 69.]
 [52. 38.  7. 58. 21.]
 [20. 23. 10. 91. 42.]
 [44. 36. 25. 45. 49.]
 [94. 51. 98. 99. 27.]]
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1.]
 [0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]
33348.0


# Part 2

In [338]:
f = open('Day4input.txt', 'r')
data = f.read()
data = data.split('\n\n')
numbers = np.array([int(i) for i in data[0].split(',')])
boards = [i.split('\n') for i in data[1:]]

In [343]:
boardsfinal = np.zeros((len(boards), 5, 5))
boardsfound = np.zeros((len(boards), 5, 5))
for m, j in enumerate(boards):
    board = [i.split(' ') for i in j]
    boardtmp = np.zeros((5, 5))
    for n,k in enumerate(board):
        boardtmp[n] = [int(i) for i in k if i != '']
    boardsfinal[m] = boardtmp

In [344]:
lostindex = 0
for i in numbers:
    hits = np.where(boardsfinal == i)
    numwon = 0
    for j in range(len(hits[0])):
        boardsfound[hits[0][j], hits[1][j], hits[2][j]] = 1
    for n, j in enumerate(boardsfound):
        Truetest1 = np.array([True for i in j if sum(i) == 5])
        Truetest2 = np.array([True for i in np.transpose(j) if sum(i) == 5])
        #print(Truetest1, Truetest2, n, i)
        if Truetest1.any() == True or Truetest2.any() ==True:
            numwon+=1
            #print(numwon, n)
        if Truetest1.any() == False and Truetest2.any() ==False:
            lostindex = n
            #print(lostindex)
        if numwon == len(boards):
            losingboard = boardsfinal[lostindex]
            losingmask = boardsfound[lostindex]
            break
    else:
        continue
    break
print(losingboard)
print(losingmask)
print(sum(sum(losingboard*(losingmask-1)*-1))*i)

[[49. 81. 31.  9. 60.]
 [33. 15. 29. 38. 66.]
 [90. 43.  2. 39. 89.]
 [24. 40. 63. 36. 91.]
 [45. 68. 62. 87. 12.]]
[[1. 1. 0. 1. 0.]
 [0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]]
8112.0
